### ISSUE TITLE
Specification Design Issues

### ISSUE THREAD

**Issue by Spomky** [web-token/jwt-framework#145]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no
| BC Break?     | no
| RFC? / Specification | no
| Version              | all

The framework covers all the specifications and also includes experimental features from drafts.
It appears that the design of these specifications leads to misuse and potential security issues.

Non-exhaustive list of misuse:

* [ ] Using JWT for session management
* [x] Mixing symmetric/asymmetric algorithms (see #150)
* [x] Mixing public/private keys in a key set (see #150)
* [x] Using weak algorithms (RSA1_5 and all non-authenticated encryption algorithms in general)
* [ ] Using vulnerable keys (low exponent, invalid curves, short keys...)
* [ ] Using/Manipulating claims that have not been correctly checked or are not really understood
* [x] Lack of logging/monitoring (#152)
    * [x] List of loaded/issued tokens
    * [x] For each loaded token
        * [x] List all checked claims and headers
        * [x] Show keys used to verify the signature or decrypt the payload
* [ ] Sensitive data exposure

This framework provides [a very limited set of classes](https://github.com/web-token/jwt-framework/tree/v1.2/src/Component/KeyManagement/KeyAnalyzer) or [collectors](https://github.com/web-token/jwt-framework/tree/v1.2/src/Bundle/JoseFramework/DataCollector) to help the developpers.
It clearly appears that it is not enough.

Additional tools should be added. These tools should be able to warn the developpers in dev and in production mode by providing e.g. reports or log messages. These tools might be grouped in a dedicated package.
Security Recommendations available in the documentation have to be updated.

The algorithms provided by this framework are split into packages by family (RSA, EC...) + experimental.
A new package might be create for all insecured algorithms (e.g. RSA1_5) that are no longer recommended.

**Comment by moderndeveloperllc** [comment]
@Spomky Thanks for the update and for the software! I'm also looking into integrating your FIDO2 library into my next project as an optional authentication method. Great stuff.

**Comment by moderndeveloperllc** [comment]
@Spomky The only thing on your list I hope you don't prevent is the "Using JWT for session management". Yes, I've read both of the diatribes against this practice, but I like my "reimplementation of sessions" and don't particularly want my libraries to be spamming me log messages - not that I'm sure how you would do that anyways. Thanks.

**Comment by Spomky** [comment]
Hi @moderndeveloperllc 

This framework makes no (and will never make) assumption on the way you use tokens.

The use of Json Web Tokens for session management is not a bad idea at all. I disagree with the trendy blog posts claiming you should avoid that. [This page](https://medium.com/@yuliaoletskaya/can-jwt-be-used-for-sessions-4164d124fe23) sums up the situation and my POV.

Actually, no log messages are sent. At the moment the monitoring is done only for Symfony App

* via the events dispatched on success/failure when parsing/computing tokens (you are free to decide if you want to listen to these events or not)
* in the Debug Toolbar.
